name: Testes Automatizados

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      # 1. Check-out do código
      - name: Check out code
        uses: actions/checkout@v3  # Atualizado para v3

      # 2. Configuração do ambiente Python
      - name: Set up Python
        uses: actions/setup-python@v4  # Atualizado para v4
        with:
          python-version: '3.13'  # Versão Python instalada

      # 3. Instalar as dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Rodar todos os testes com pytest
      - name: Run all tests
        run: |
          pytest -v  
