name: Testes Automatizados

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest  
    steps:
      # 1. Check-out do código
      - name: Check out code
        uses: actions/checkout@v2

      # 2. Configuração do ambiente Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13.0'  
      # 3. Instalar as dependências 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  

      # 4. Rodar os testes
      - name: Run tests
        run: |
          python acessar.py
          python adicionar.py
          python carregamento.py
          python carrinho.py
          python categorias.py
          python elemento.py
          python footer.py
          python menu.py
          python pesquisa.py
          python preco.py
          python quantidade.py
          python responsividade.py
          python texto.py
          python titulo.py
          python url.py  
