name: Testes Automatizados

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest  
    steps:
      # 1. Check-out do código
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Supondo que você tenha um arquivo requirements.txt

      - name: Run tests
        run: |
          pytest  
