name: Testes Automatizados

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    runs-on: windows-latest  # Executa em um ambiente Windows

    steps:
      # 1. Check-out do código
      - name: Check out code
        uses: actions/checkout@v2

      # 2. Configuração do Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13.0'

      # 3. Instalar dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

            # 4. Baixar e configurar o Microsoft Edge WebDriver
      - name: Set up Microsoft Edge WebDriver
        run: |
          # Baixar a versão mais recente do Edge WebDriver diretamente do site oficial
          Invoke-WebRequest -Uri "https://msedgedriver.azureedge.net/117.0.2045.47/edgedriver_win64.zip" -OutFile edgedriver.zip
          Expand-Archive -Path edgedriver.zip -DestinationPath .
          Remove-Item -Force edgedriver.zip
          # Adicionar o WebDriver ao PATH
          $env:Path += ";$PWD"


      # 5. Rodar os testes
      - name: Run tests
        run: |
          pytest
